// Syncs free content packs from the sibling bacchana-content repo into src/content/.
// Reproducible, idempotent: safe to re-run at any time.
//
// - Copies packs with pack.premium === false (store-safe, public repo, gratuit) as-is.
// - Premium packs are NEVER copied here (served later via Supabase, M6). Only their
//   metadata (id, mode, title, subtitle, intensity, premium, item count) is extracted
//   into src/content/premium-catalog.json so the hub can display locked tiles.
// - Regenerates src/content/index.ts with typed imports of every free pack.
//
// Usage: node scripts/outils/sync-content.mjs
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const sourceDir = join(root, '..', 'bacchana-content', 'content', 'fr', 'packs')
const targetDir = join(root, 'src', 'content', 'packs')

// LA SOURCE SE VERIFIE AVANT TOUT MENAGE, et l'ordre inverse a coute les six
// paquets du depot le 2026-09-13. Le script effacait `src/content/packs`, PUIS
// lisait le depot de contenu ; lance sans ce depot a cote - ce qui est le cas
// par defaut sur une machine neuve, et de tout agent qui ne l'a pas clone - il
// vidait le contenu de l'application avant de mourir sur un ENOENT. Le message
// d'erreur parlait de `scandir`, jamais des 480 cartes qui venaient de
// disparaitre.
if (!existsSync(sourceDir)) {
  console.error(
    `Depot de contenu introuvable : ${sourceDir}\n` +
      "Clone `bacchana-content` a cote de ce depot, ou lance la synchro depuis la\n" +
      'machine qui le porte. Aucun fichier n\'a ete touche.'
  )
  process.exit(1)
}

const files = readdirSync(sourceDir).filter((f) => f.endsWith('.json')).sort()

mkdirSync(targetDir, { recursive: true })
// Clean previously synced packs so removed/renamed source packs do not linger.
for (const file of readdirSync(targetDir)) {
  if (file.endsWith('.json')) rmSync(join(targetDir, file))
}

const freePacks = []
const premiumCatalog = []

for (const file of files) {
  const raw = readFileSync(join(sourceDir, file), 'utf-8')
  const parsed = JSON.parse(raw)
  const { pack, items } = parsed

  if (pack.premium) {
    premiumCatalog.push({
      id: pack.id,
      mode: pack.mode,
      title: pack.title,
      subtitle: pack.subtitle ?? '',
      intensity: pack.intensity ?? 'medium',
      premium: true,
      itemCount: items.length,
    })
    continue
  }

  writeFileSync(join(targetDir, file), raw)
  freePacks.push({
    file,
    id: pack.id,
    mode: pack.mode,
    title: pack.title,
    subtitle: pack.subtitle ?? '',
    intensity: pack.intensity ?? 'medium',
    minPlayers: pack.minPlayers ?? null,
    itemCount: items.length,
  })
}

freePacks.sort((a, b) => a.id.localeCompare(b.id))

// DEUX fichiers generes, et c'est la seule raison pour laquelle ce script a
// change le 2026-09-13.
//
// `index.ts` ne porte que le MANIFESTE : identifiant, mode, titre, nombre de
// cartes. Quelques lignes de metadonnees, aucun import de JSON.
// `paquets.ts` porte les CARTES, et n'est importe que par ce qui en sert
// vraiment - l'ecran d'accueil et les tests.
//
// Le defaut mesure : `modeRegistry` importait les paquets entiers pour repondre
// « quels paquets gratuits existent pour ce mode ? ». Le registre etant
// atteignable depuis `App`, les 92 Ko de cartes des six paquets partaient dans
// le morceau d'entree, telecharges avant meme l'ecran d'accueil - pour une
// information qui tient en six identifiants.
const manifesteLines = [
  '// AUTO-GENERATED by scripts/outils/sync-content.mjs - do not edit by hand.',
  "import type { GameMode, Intensity } from '@/core/engine/types'",
  '',
  '/** Ce qu\'on sait d\'un paquet SANS ouvrir ses cartes. */',
  'export interface ResumePaquet {',
  '  id: string',
  '  mode: GameMode',
  '  title: string',
  '  subtitle: string',
  '  intensity: Intensity',
  '  /** Tablee minimale exigee par le paquet, quand il en declare une. */',
  '  minPlayers: number | null',
  '  nbCartes: number',
  '}',
  '',
  '/**',
  ' * Les paquets gratuits, en metadonnees seulement.',
  ' *',
  " * A importer partout ou l'on a besoin de SAVOIR quels paquets existent. Les",
  " * cartes elles-memes vivent dans `./paquets`, qui pese 92 Ko et n'a rien a",
  ' * faire dans le chemin de demarrage.',
  ' */',
  'export const MANIFESTE_PAQUETS: ResumePaquet[] = [',
  ...freePacks.map(
    (p) =>
      `  { id: ${JSON.stringify(p.id)}, mode: ${JSON.stringify(p.mode)}, title: ${JSON.stringify(p.title)}, ` +
      `subtitle: ${JSON.stringify(p.subtitle)}, intensity: ${JSON.stringify(p.intensity)}, ` +
      `minPlayers: ${p.minPlayers === null ? 'null' : p.minPlayers}, nbCartes: ${p.itemCount} },`
  ),
  ']',
  '',
]

const paquetsLines = [
  '// AUTO-GENERATED by scripts/outils/sync-content.mjs - do not edit by hand.',
  '//',
  '// LES CARTES. Ce module pese le poids du contenu : ne l\'importer que depuis',
  '// un ecran deja charge a la demande, jamais depuis le registre ni depuis quoi',
  '// que ce soit qu\'`App` atteigne au demarrage. Voir `MANIFESTE_PAQUETS` dans',
  '// ./index pour la version en metadonnees.',
  "import type { ContentPack } from '@/core/engine/types'",
  '',
  ...freePacks.map((p, i) => `import pack${i} from './packs/${p.file}'`),
  '',
  '/** Every free (non-premium) content pack, typed and bundled at build time. */',
  `export const FREE_PACKS: ContentPack[] = [${freePacks.map((_, i) => `pack${i}`).join(', ')}] as ContentPack[]`,
  '',
]

writeFileSync(join(root, 'src', 'content', 'index.ts'), manifesteLines.join('\n'))
writeFileSync(join(root, 'src', 'content', 'paquets.ts'), paquetsLines.join('\n'))
writeFileSync(
  join(root, 'src', 'content', 'premium-catalog.json'),
  JSON.stringify(premiumCatalog, null, 2) + '\n'
)

console.log(`synced ${freePacks.length} free packs, catalogued ${premiumCatalog.length} premium packs`)
