// AUTO-GENERATED by scripts/outils/sync-content.mjs - do not edit by hand.
import type { GameMode, Intensity } from '@/core/engine/types'

/** Ce qu'on sait d'un paquet SANS ouvrir ses cartes. */
export interface ResumePaquet {
  id: string
  mode: GameMode
  title: string
  subtitle: string
  intensity: Intensity
  /** Tablee minimale exigee par le paquet, quand il en declare une. */
  minPlayers: number | null
  nbCartes: number
}

/**
 * Les paquets gratuits, en metadonnees seulement.
 *
 * A importer partout ou l'on a besoin de SAVOIR quels paquets existent. Les
 * cartes elles-memes vivent dans `./paquets`, qui pese 92 Ko et n'a rien a
 * faire dans le chemin de demarrage.
 */
export const MANIFESTE_PAQUETS: ResumePaquet[] = [
  { id: "action-verite-classique", mode: "truthOrDare", title: "Action ou Vérité - Classique", subtitle: "Choisis ton camp", intensity: "soft", minPlayers: null, nbCartes: 80 },
  { id: "cest-un-10-classique", mode: "itsA10But", title: "C'est un 10 mais - Classique", subtitle: "Le deal-breaker ultime", intensity: "medium", minPlayers: null, nbCartes: 80 },
  { id: "never-classique", mode: "neverHaveIEver", title: "Je n'ai jamais - Classique", subtitle: "Avoue si tu l'as déjà fait", intensity: "soft", minPlayers: null, nbCartes: 80 },
  { id: "picolo-soiree", mode: "picolo", title: "Le Taulier - Soirée", subtitle: "Le meneur de jeu de ta soirée", intensity: "medium", minPlayers: 3, nbCartes: 80 },
  { id: "qui-de-nous-classique", mode: "whoAmong", title: "Qui de nous - Classique", subtitle: "Désigne le coupable", intensity: "soft", minPlayers: 3, nbCartes: 80 },
  { id: "sept-secondes-classique", mode: "sevenSeconds", title: "7 Secondes - Classique", subtitle: "Réponds vite ou prends une pénalité", intensity: "soft", minPlayers: null, nbCartes: 80 },
]
