// AUTO-GENERATED by scripts/sync-content.mjs - do not edit by hand.
import type { ContentPack } from '@/core/engine/types'

import pack0 from './packs/action-verite-classique.json'
import pack1 from './packs/cest-un-10-classique.json'
import pack2 from './packs/never-classique.json'
import pack3 from './packs/picolo-soiree.json'
import pack4 from './packs/qui-de-nous-classique.json'
import pack5 from './packs/sept-secondes-classique.json'

/** Every free (non-premium) content pack, typed and bundled at build time. */
export const FREE_PACKS: ContentPack[] = [pack0, pack1, pack2, pack3, pack4, pack5] as ContentPack[]
