// Syncs free content packs from the sibling la-taverne-content repo into src/content/.
// Reproducible, idempotent: safe to re-run at any time.
//
// - Copies packs with pack.premium === false (store-safe, public repo, gratuit) as-is.
// - Premium packs are NEVER copied here (served later via a backend, M6). Only their
//   metadata (id, mode, title, subtitle, intensity, premium, item count) is extracted
//   into src/content/premium-catalog.json so the hub can display locked tiles.
// - Regenerates src/content/index.ts with typed imports of every free pack.
//
// Usage: node scripts/sync-content.mjs
import { mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const sourceDir = join(root, '..', 'la-taverne-content', 'content', 'fr', 'packs')
const targetDir = join(root, 'src', 'content', 'packs')

mkdirSync(targetDir, { recursive: true })
// Clean previously synced packs so removed/renamed source packs do not linger.
for (const file of readdirSync(targetDir)) {
  if (file.endsWith('.json')) rmSync(join(targetDir, file))
}

const files = readdirSync(sourceDir).filter((f) => f.endsWith('.json')).sort()

const freePacks = []
const premiumCatalog = []

for (const file of files) {
  const raw = readFileSync(join(sourceDir, file), 'utf-8')
  const parsed = JSON.parse(raw)
  const { pack, items } = parsed

  if (pack.premium) {
    premiumCatalog.push({
      id: pack.id,
      mode: pack.mode,
      title: pack.title,
      subtitle: pack.subtitle ?? '',
      intensity: pack.intensity ?? 'medium',
      premium: true,
      itemCount: items.length,
    })
    continue
  }

  writeFileSync(join(targetDir, file), raw)
  freePacks.push({ file, id: pack.id })
}

freePacks.sort((a, b) => a.id.localeCompare(b.id))

const indexLines = [
  '// AUTO-GENERATED by scripts/sync-content.mjs - do not edit by hand.',
  "import type { ContentPack } from '@/core/engine/types'",
  '',
  ...freePacks.map(
    (p, i) => `import pack${i} from './packs/${p.file}'`
  ),
  '',
  '/** Every free (non-premium) content pack, typed and bundled at build time. */',
  `export const FREE_PACKS: ContentPack[] = [${freePacks.map((_, i) => `pack${i}`).join(', ')}] as ContentPack[]`,
  '',
]

writeFileSync(join(root, 'src', 'content', 'index.ts'), indexLines.join('\n'))
writeFileSync(
  join(root, 'src', 'content', 'premium-catalog.json'),
  JSON.stringify(premiumCatalog, null, 2) + '\n'
)

console.log(`synced ${freePacks.length} free packs, catalogued ${premiumCatalog.length} premium packs`)
