// Les noms sont des INTENTIONS, pas des dessins : `quitter`, pas `porte`.
// C'est ce qui a permis de changer quatre fois de jeu d'icones sans toucher un
// seul appel a <Icon name="..." />. La correspondance vers les dessins Reicon,
// et les choix qui ne vont pas de soi, sont dans la table GLYPHES d'Icon.tsx.

export const ICON_NAMES = [
  'accueil',
  'aide',
  'ajouter-joueur',
  'appui',
  'balance',
  'bouclier',
  'cadenas',
  'cadran',
  'carreau',
  'cerveau',
  'chargement',
  'chronometre',
  'chut',
  'coeur',
  'cookie',
  'couronne',
  'curseurs',
  'des',
  'ecrire',
  'editer',
  'epee',
  'etincelles',
  'etoile',
  'fermer',
  'fete',
  'flamme',
  'gemme',
  'horloge',
  'hors-ligne',
  'infini',
  'info',
  'jouer',
  'joueurs',
  'livre',
  'lune',
  'main-levee',
  'marteau-juge',
  'masque',
  'medaille',
  'megaphone',
  'moins',
  'oeil',
  'oeil-barre',
  'paquets',
  'partager',
  'pique',
  'plus',
  'pouce-bas',
  'pouce-haut',
  'quitter',
  'recommencer',
  'reglages',
  'retour',
  'roue',
  'soleil',
  'suivant',
  'supprimer',
  'ticket',
  'trefle',
  'valider',
  'vote',
] as const

export type IconName = (typeof ICON_NAMES)[number]
