// Genere par scripts/vendor_icons8.py. Ne pas editer a la main.
// Relancer : python scripts/vendor_icons8.py

export const ICON_NAMES = [
  'accueil',
  'aide',
  'ajouter-joueur',
  'balance',
  'bouclier',
  'cadenas',
  'carreau',
  'cerveau',
  'chargement',
  'chronometre',
  'coeur',
  'cookie',
  'couronne',
  'curseurs',
  'des',
  'ecrire',
  'editer',
  'epee',
  'etincelles',
  'fermer',
  'fete',
  'flamme',
  'gemme',
  'horloge',
  'hors-ligne',
  'infini',
  'info',
  'jouer',
  'joueurs',
  'livre',
  'lune',
  'main-levee',
  'marteau-juge',
  'medaille',
  'megaphone',
  'moins',
  'oeil',
  'oeil-barre',
  'paquets',
  'partager',
  'pique',
  'plus',
  'pouce-bas',
  'pouce-haut',
  'quitter',
  'recommencer',
  'reglages',
  'regles',
  'retour',
  'roue',
  'soleil',
  'suivant',
  'supprimer',
  'ticket',
  'trefle',
  'valider',
] as const

export type IconName = (typeof ICON_NAMES)[number]
